# Generated by Django 5.2.17 on 2026-10-01 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(choices=[('help', 'I need help using SplitStay'), ('payment', 'A payment or payout question'), ('bug', "Something isn't working"), ('idea', 'An idea or feedback'), ('other', 'Something else')], default='help', max_length=10)),
                ('message', models.TextField(max_length=4000)),
                ('reference', models.CharField(blank=True, help_text='Group name or payment reference, if any', max_length=60)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
