# Generated by Django 5.2.17 on 2026-09-29 18:17

import apps.contributions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('reference', models.CharField(default=apps.contributions.models.new_reference, editable=False, max_length=40, unique=True)),
                ('gateway', models.CharField(blank=True, max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='groups.contributiongroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'status'], name='contributio_group_i_b09129_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='contribution_amount_positive')],
            },
        ),
    ]
