# Generated by Django 5.2.17 on 2026-09-29 18:17

import apps.accounts.fields
import apps.payouts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billpay', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('reference', models.CharField(default=apps.payouts.models.new_payout_reference, max_length=60, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('gateway', models.CharField(blank=True, max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=250)),
                ('is_partial', models.BooleanField(default=False)),
                ('recipient_bank_code', models.CharField(max_length=10)),
                ('recipient_bank_name', models.CharField(max_length=100)),
                ('recipient_account_name', models.CharField(max_length=150)),
                ('recipient_account_number', apps.accounts.fields.EncryptedTextField()),
                ('recipient_account_last4', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='groups.contributiongroup')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percentage')], max_length=8)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Naira if flat, percent if percentage', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(default='SplitStay service fee', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='billpay.billpayment')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='payouts.payout')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gt', 0)), name='payout_net_positive'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bill_payment__isnull', True), ('payout__isnull', False)), models.Q(('bill_payment__isnull', False), ('payout__isnull', True)), _connector='OR'), name='fee_belongs_to_exactly_one'),
        ),
    ]
