# Generated by Django 5.2.17 on 2026-09-29 18:17

import apps.accounts.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity (NEPA)'), ('subscription', 'Subscription'), ('family_upkeep', 'Family upkeep'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('funded', 'Funded'), ('paid_out', 'Paid out'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], db_index=True, default='open', max_length=10)),
                ('payout_type', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('bill_payment', 'Bill payment')], max_length=15)),
                ('allow_partial_payout', models.BooleanField(default=False)),
                ('bill_service_id', models.CharField(blank=True, help_text='Biller code, e.g. ikeja-electric', max_length=60)),
                ('bill_customer_id', models.CharField(blank=True, help_text='Meter number / smartcard / account', max_length=40)),
                ('bill_variation', models.CharField(blank=True, help_text='prepaid / postpaid', max_length=20)),
                ('recipient_bank_code', models.CharField(blank=True, max_length=10)),
                ('recipient_bank_name', models.CharField(blank=True, max_length=100)),
                ('recipient_account_name', models.CharField(blank=True, max_length=150)),
                ('recipient_account_number', apps.accounts.fields.EncryptedTextField(blank=True, default='')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('series_anchor_date', models.DateField(help_text='Due date of cycle 1; later cycles are offset from it')),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_groups', to=settings.AUTH_USER_MODEL)),
                ('previous_cycle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_cycle', to='groups.contributiongroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_custom_share', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('left', 'Left')], default='invited', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.contributiongroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contributiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='group_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='contributiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('is_recurring', False), ('recurrence_interval__isnull', False), _connector='OR'), name='group_recurring_needs_interval'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_member'),
        ),
    ]
