# Generated by Django 5.2.17 on 2026-09-29 18:17

import apps.billpay.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount actually sent to the biller', max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('reference', models.CharField(default=apps.billpay.models.new_bill_reference, max_length=60, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('service_id', models.CharField(max_length=60)),
                ('customer_id', models.CharField(max_length=40)),
                ('variation', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('token', models.CharField(blank=True, help_text='Electricity token, when applicable', max_length=100)),
                ('units', models.CharField(blank=True, max_length=40)),
                ('failure_reason', models.CharField(blank=True, max_length=250)),
                ('is_partial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payment', to='groups.contributiongroup')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('net_amount__gt', 0)), name='billpay_net_positive')],
            },
        ),
    ]
